import {
  BrandingSettings,
  Destination,
  FeatureFlags,
  HomepageSection,
  Hotel,
  PolicySettings,
  RoomType,
  ServiceItem,
  TourPackage,
  Coupon,
  Banner,
} from '../types';

export const defaultBranding: BrandingSettings = {
  brandName: 'Travelly',
  tagline: 'Your Global Journey Awaits. Discover Luxury Stays & Escapes.',
  logoUrl: '/icons/icon-192.png',
  primaryColor: '#0b1120',
  accentColor: '#0284c7',
  contactEmail: 'support@travelly.com',
  contactPhone: '+91 98765 43210',
  address: 'Travelly Tower, Connaught Place, New Delhi - 110001, India',
  socialLinks: {
    facebook: 'https://facebook.com',
    twitter: 'https://twitter.com',
    instagram: 'https://instagram.com',
    linkedin: 'https://linkedin.com',
  },
  footerLinks: [
    {
      title: 'Company',
      links: [
        { label: 'About Us', url: '/#why_choose_us' },
        { label: 'Careers', url: '#' },
        { label: 'Travel Blog', url: '#' },
        { label: 'Press & Media', url: '#' },
      ],
    },
    {
      title: 'Explore',
      links: [
        { label: 'Luxury Hotels', url: '/hotels' },
        { label: 'Tour Packages', url: '/packages' },
        { label: 'Travel Services & Cabs', url: '/services' },
        { label: 'Trending Destinations', url: '/#trending_destinations' },
      ],
    },
    {
      title: 'Customer Care',
      links: [
        { label: 'My Bookings', url: '/trips' },
        { label: 'Customer Support', url: '#' },
        { label: 'FAQs', url: '#' },
        { label: 'Cancellation Policy', url: '/terms' },
      ],
    },
    {
      title: 'Legal',
      links: [
        { label: 'Privacy Policy', url: '/privacy' },
        { label: 'Terms & Conditions', url: '/terms' },
        { label: 'Security & Safety', url: '/privacy' },
      ],
    },
  ],
};

export const defaultSections: HomepageSection[] = [
  {
    id: 'hero',
    name: 'Hero Search Banner',
    type: 'hero',
    title: 'Find Your Perfect Escape',
    subtitle: 'Search luxury hotels, boutique resorts, and curated tour packages with best price guarantee.',
    enabled: true,
    order: 1,
  },
  {
    id: 'trending_destinations',
    name: 'Trending Destinations',
    type: 'trending_destinations',
    title: 'Trending Getaways',
    subtitle: 'Top handpicked destinations travelers are visiting right now.',
    enabled: true,
    order: 2,
  },
  {
    id: 'offers_banner',
    name: 'Special Offers',
    type: 'offers_banner',
    title: 'Deals & Seasonal Offers',
    subtitle: 'Unlock extra savings with exclusive promo codes and limited-time package sales.',
    enabled: true,
    order: 3,
  },
  {
    id: 'featured_hotels',
    name: 'Featured Luxury Hotels',
    type: 'featured_hotels',
    title: 'Handpicked Luxury Stays',
    subtitle: 'Verified premium properties offering unmatched comfort, gourmet dining, and spectacular views.',
    enabled: true,
    order: 4,
  },
  {
    id: 'popular_packages',
    name: 'Popular Tour Packages',
    type: 'popular_packages',
    title: 'Curated Holiday Packages',
    subtitle: 'All-inclusive, worry-free holidays planned by certified travel specialists.',
    enabled: true,
    order: 5,
  },
  {
    id: 'why_choose_us',
    name: 'Why Choose Us',
    type: 'why_choose_us',
    title: 'Why Book With Travelly',
    subtitle: 'Transparent prices, zero hidden fees, and 24/7 concierge support every mile of your trip.',
    enabled: true,
    order: 6,
  },
  {
    id: 'testimonials',
    name: 'Guest Testimonials',
    type: 'testimonials',
    title: 'Loved by Over 500,000 Travelers',
    subtitle: 'Real stories and verified experiences from guests who explored with Travelly.',
    enabled: true,
    order: 7,
  },
];

export const defaultFeatureFlags: FeatureFlags = {
  enableOnlinePayment: true,
  enableReviews: true,
  enableAgents: true,
  maintenanceMode: false,
  bannerMessage: '🎉 Summer Flash Sale: Use code SUMMER2026 for flat ₹1,500 off on holiday packages!',
};

export const defaultPolicies: PolicySettings = {
  defaultCancellationHours: 24,
  standardTaxPercent: 12,
  currency: 'INR',
  currencySymbol: '₹',
};

export const sampleDestinations: Destination[] = [
  {
    id: 'dest_goa',
    name: 'Goa',
    state: 'Goa',
    country: 'India',
    description: 'Golden beaches, vibrant nightlife, Portuguese heritage, and coastal seafood shacks.',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    popular: true,
    order: 1,
    hotelCount: 24,
    packageCount: 8,
  },
  {
    id: 'dest_jaipur',
    name: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    description: 'The Pink City: royal palaces, majestic forts, bustling bazaars, and opulent heritage stays.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
    popular: true,
    order: 2,
    hotelCount: 18,
    packageCount: 6,
  },
  {
    id: 'dest_kerala',
    name: 'Kerala',
    state: 'Kerala',
    country: 'India',
    description: 'God\'s Own Country: tranquil backwaters, emerald tea plantations, and ayurvedic sanctuaries.',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80',
    popular: true,
    order: 3,
    hotelCount: 22,
    packageCount: 7,
  },
  {
    id: 'dest_manali',
    name: 'Manali',
    state: 'Himachal Pradesh',
    country: 'India',
    description: 'Snow-capped peaks, pine forests, adventure sports in Solang Valley, and riverside chalets.',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
    popular: true,
    order: 4,
    hotelCount: 19,
    packageCount: 5,
  },
  {
    id: 'dest_udaipur',
    name: 'Udaipur',
    state: 'Rajasthan',
    country: 'India',
    description: 'City of Lakes: romantic marble palaces rising from glistening Lake Pichola water.',
    image: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=800&q=80',
    popular: true,
    order: 5,
    hotelCount: 15,
    packageCount: 4,
  },
  {
    id: 'dest_dubai',
    name: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    description: 'Futuristic skyline, world-record shopping malls, desert dunes, and ultra-luxurious hospitality.',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80',
    popular: true,
    order: 6,
    hotelCount: 30,
    packageCount: 9,
  },
];

export const sampleHotels: (Hotel & { rooms: RoomType[] })[] = [
  {
    id: 'hotel_grand_horizon_goa',
    name: 'The Grand Horizon Luxury Resort & Spa',
    slug: 'the-grand-horizon-luxury-resort-spa-goa',
    destinationId: 'dest_goa',
    destinationCity: 'Goa',
    starRating: 5,
    propertyType: 'resort',
    description: 'Situated on the pristine shores of South Goa, The Grand Horizon combines Portuguese colonial architecture with state-of-the-art modern comforts. Features two beachfront infinity pools, an Ayurvedic spa, four fine-dining restaurants, and complimentary water activities.',
    address: 'Varca Beach Road, South Goa, Goa 403721',
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Beachfront Access',
      'Infinity Pool',
      'Full-Service Spa',
      'High-Speed Wi-Fi',
      'Free Valet Parking',
      'Kids Play Area',
      'Airport Shuttle',
      'Cocktail Bar',
      'Breakfast Included',
    ],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '11:00',
      cancellationPolicy: 'Free cancellation up to 24 hours before check-in date.',
      houseRules: [
        'Government ID required at check-in.',
        'Pets allowed in dedicated beachfront villas upon prior request.',
        'Non-smoking in all indoor suites.',
      ],
    },
    isPublished: true,
    minPrice: 7499,
    featured: true,
    rooms: [
      {
        id: 'room_gh_deluxe_ocean',
        hotelId: 'hotel_grand_horizon_goa',
        name: 'Deluxe Ocean View Room',
        description: 'Spacious 450 sq.ft room with a private balcony overlooking the Arabian Sea, plush king bed, marble bath with rain shower.',
        maxGuests: 2,
        bedType: '1 King Bed',
        basePrice: 7499,
        amenities: ['Sea View Balcony', 'Bathtub', 'Smart TV', 'Espresso Machine', 'Mini Bar'],
        images: [
          'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
        ],
        totalInventory: 10,
        isAvailable: true,
      },
      {
        id: 'room_gh_royal_suite',
        hotelId: 'hotel_grand_horizon_goa',
        name: 'Royal Ocean Suite with Jacuzzi',
        description: 'Luxurious 800 sq.ft suite with private sundeck, heated outdoor Jacuzzi, dedicated butler service, and complimentary sunset cocktails.',
        maxGuests: 4,
        bedType: '1 King Bed + 1 Queen Sofa Bed',
        basePrice: 13999,
        amenities: ['Private Jacuzzi', 'Butler Service', 'Living Room', 'Walk-in Closet', 'Complimentary Wine'],
        images: [
          'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
        ],
        totalInventory: 5,
        isAvailable: true,
      },
    ],
  },
  {
    id: 'hotel_heritage_haveli_jaipur',
    name: 'Heritage Haveli Palace & Retreat',
    slug: 'heritage-haveli-palace-retreat-jaipur',
    destinationId: 'dest_jaipur',
    destinationCity: 'Jaipur',
    starRating: 5,
    propertyType: 'hotel',
    description: 'A restored 200-year-old Rajput architectural marvel boasting hand-painted frescoes, courtyards with fountains, rooftop dining overlooking Amber Fort hills, and evening traditional folk dance performances.',
    address: 'Amer Road, Pink City, Jaipur, Rajasthan 302002',
    images: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1561501900-3701fa6a0864?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Royal Courtyard',
      'Rooftop Restaurant',
      'Swimming Pool',
      'Cultural Performances',
      'Free High-Speed Wi-Fi',
      'Spa & Ayurveda',
      '24h Room Service',
    ],
    policies: {
      checkInTime: '13:00',
      checkOutTime: '11:00',
      cancellationPolicy: 'Free cancellation up to 48 hours before check-in date.',
      houseRules: ['Valid Passport or Aadhaar required.', 'No outside food inside courtyard.'],
    },
    isPublished: true,
    minPrice: 5999,
    featured: true,
    rooms: [
      {
        id: 'room_hh_courtyard_room',
        hotelId: 'hotel_heritage_haveli_jaipur',
        name: 'Heritage Courtyard Room',
        description: 'Authentic royal Rajasthani decor with antique rosewood furniture, courtyard fountain view, and modern luxury bathroom.',
        maxGuests: 2,
        bedType: '1 King Four-Poster Bed',
        basePrice: 5999,
        amenities: ['Courtyard View', 'Tea Maker', 'Handcrafted Furniture', 'High-Speed Wi-Fi'],
        images: [
          'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
        ],
        totalInventory: 8,
        isAvailable: true,
      },
      {
        id: 'room_hh_maharaja_suite',
        hotelId: 'hotel_heritage_haveli_jaipur',
        name: 'Maharaja Presidential Suite',
        description: 'Grand royal chambers with gold leaf detailing, private terrace overlooking Amber hills, living salon, and antique brass bathtub.',
        maxGuests: 3,
        bedType: '1 Royal Grand Bed',
        basePrice: 11499,
        amenities: ['Private Terrace', 'Panoramic Hill View', 'Antique Tub', 'Personal Concierge'],
        images: [
          'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80',
        ],
        totalInventory: 4,
        isAvailable: true,
      },
    ],
  },
  {
    id: 'hotel_whispering_pines_manali',
    name: 'Whispering Pines Alpine Chalet & Spa',
    slug: 'whispering-pines-alpine-chalet-manali',
    destinationId: 'dest_manali',
    destinationCity: 'Manali',
    starRating: 4,
    propertyType: 'resort',
    description: 'Nestled among dense cedar and pine forests with panoramic vistas of the snow-clad Pir Panjal mountains. Features wooden warm interiors, indoor heated pools, bonfire evenings, and guided mountain treks.',
    address: 'Old Manali Hills, Manali, Himachal Pradesh 175131',
    images: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Snow Peak Views',
      'Fireplace in Lounge',
      'Heated Pool',
      'Bonfire & BBQ',
      'Games Room',
      'Free Parking',
      'Trek Guide Desk',
    ],
    policies: {
      checkInTime: '12:00',
      checkOutTime: '10:00',
      cancellationPolicy: 'Free cancellation up to 24 hours before check-in date.',
      houseRules: ['Heaters included in room fare.', 'Quiet hours after 22:30.'],
    },
    isPublished: true,
    minPrice: 4299,
    featured: true,
    rooms: [
      {
        id: 'room_wp_pine_chalet',
        hotelId: 'hotel_whispering_pines_manali',
        name: 'Alpine Pine View Chalet',
        description: 'Warm pinewood decor, private glass-fronted balcony with majestic Himalayan mountain view, electric heating blanket, and hot shower.',
        maxGuests: 2,
        bedType: '1 Queen Bed',
        basePrice: 4299,
        amenities: ['Mountain Balcony', 'Room Heater', 'Electric Kettle', 'Wi-Fi'],
        images: [
          'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=80',
        ],
        totalInventory: 12,
        isAvailable: true,
      },
    ],
  },
  {
    id: 'hotel_coconut_lagoon_kerala',
    name: 'Coconut Lagoon Backwater Retreat',
    slug: 'coconut-lagoon-backwater-retreat-kerala',
    destinationId: 'dest_kerala',
    destinationCity: 'Kerala',
    starRating: 5,
    propertyType: 'resort',
    description: 'Accessible exclusively by traditional wooden boat across Vembanad Lake. Features authentic Kerala heritage timber bungalows, butterfly gardens, tranquil lotus ponds, and sunset classical music cruises.',
    address: 'Kumarakom, Kottayam, Kerala 686563',
    images: [
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Private Boat Arrival',
      'Ayurvedic Center',
      'Lakefront Dining',
      'Swimming Pool',
      'Yoga Pavillion',
      'Bird Watching',
      'Organic Farm',
    ],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '11:00',
      cancellationPolicy: 'Free cancellation up to 48 hours before check-in date.',
      houseRules: ['Boat transfers run every 30 minutes from landing jetty.'],
    },
    isPublished: true,
    minPrice: 8999,
    featured: true,
    rooms: [
      {
        id: 'room_cl_heritage_bungalow',
        hotelId: 'hotel_coconut_lagoon_kerala',
        name: 'Heritage Lakeview Bungalow',
        description: 'Reconstructed 100-year-old wooden Kerala tharavadu cottage with open-to-sky shower garden and veranda facing the lake canals.',
        maxGuests: 3,
        bedType: '1 King Bed',
        basePrice: 8999,
        amenities: ['Open-air Bathroom', 'Lake Veranda', 'Ayurvedic Toiletries', 'Wi-Fi'],
        images: [
          'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
        ],
        totalInventory: 6,
        isAvailable: true,
      },
    ],
  },
];

export const samplePackages: TourPackage[] = [
  {
    id: 'pkg_kerala_backwaters',
    title: 'Enchanting Kerala: Backwaters, Tea Gardens & Houseboat Cruise',
    slug: 'enchanting-kerala-backwaters-tea-gardens-houseboat',
    destinationId: 'dest_kerala',
    destinationName: 'Kerala',
    agentName: 'SpiceRoute Expeditions',
    durationDays: 5,
    durationNights: 4,
    pricePerTraveller: 18999,
    originalPrice: 24999,
    maxGroupSize: 12,
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Cochin & Scenic Drive to Munnar',
        description: 'Meet our local tour manager at Cochin Airport or Railway Station. Scenic 4-hour drive past cascading Cheeyappara and Valara waterfalls. Check in to Munnar hill resort and enjoy evening stroll through spice markets.',
        meals: ['Dinner'],
        hotelStay: 'Munnar Tea Hills Resort',
      },
      {
        day: 2,
        title: 'Munnar Tea Estate Tour & Eravikulam Wildlife Safari',
        description: 'Morning visit to Eravikulam National Park (home to the endangered Nilgiri Tahr). Afternoon tour of Tata Tea Museum and tea tasting session. Photo stop at Mattupetty Dam and Echo Point.',
        meals: ['Breakfast', 'Dinner'],
        hotelStay: 'Munnar Tea Hills Resort',
      },
      {
        day: 3,
        title: 'Munnar to Thekkady: Spice Gardens & Periyar Boat Safari',
        description: 'Drive along Western Ghats to Thekkady. Afternoon guided organic spice plantation walk learning about cardamom, cinnamon, and pepper. Evening cruise on Lake Periyar to spot wild elephants.',
        meals: ['Breakfast', 'Dinner'],
        hotelStay: 'Greenwoods Nature Resort Thekkady',
      },
      {
        day: 4,
        title: 'Thekkady to Alleppey: Private Houseboat Backwaters Cruise',
        description: 'Board your private luxury traditional Kettuvallam houseboat at Alleppey jetty by 12:30 PM. Glide through tranquil backwater lagoons, paddy fields, and coir villages while your personal chef prepares fresh traditional Karimeen fish and Malabar meals.',
        meals: ['Breakfast', 'Lunch', 'Dinner'],
        hotelStay: 'Luxury AC Houseboat Alleppey',
      },
      {
        day: 5,
        title: 'Houseboat Check-out & Departure from Cochin',
        description: 'Enjoy early morning sunrise over the lake waters. Check out after breakfast and transfer to Cochin Airport for your return flight with unforgettable memories.',
        meals: ['Breakfast'],
      },
    ],
    inclusions: [
      '4 Nights accommodation in verified 4-star resorts & luxury AC houseboat',
      'Daily delicious breakfast and dinner (All meals on Houseboat)',
      'All airport/railway transfers and sightseeing by private AC sedan/SUV',
      'Lake Periyar boat safari tickets & Tea Museum entry fees',
      'Toll taxes, parking fees, driver allowance, and GST',
    ],
    exclusions: [
      'Airfare or train tickets',
      'Personal expenses, laundry, and drinks',
      'Optional adventure activities or Ayurveda massages',
    ],
    departureDates: ['2026-10-15', '2026-10-22', '2026-11-05', '2026-11-19', '2026-12-03'],
    images: [
      'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1506461883276-594a12b11cf3?auto=format&fit=crop&w=1200&q=80',
    ],
    isPublished: true,
    featured: true,
  },
  {
    id: 'pkg_rajasthan_heritage',
    title: 'Royal Rajasthan Heritage Odyssey: Jaipur, Jodhpur & Udaipur',
    slug: 'royal-rajasthan-heritage-odyssey',
    destinationId: 'dest_jaipur',
    destinationName: 'Jaipur & Udaipur',
    agentName: 'Rajputana Royal Tours',
    durationDays: 6,
    durationNights: 5,
    pricePerTraveller: 22499,
    originalPrice: 28999,
    maxGroupSize: 10,
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Jaipur - The Pink City Welcome',
        description: 'Traditional garland welcome at Jaipur Airport. Check in to your heritage hotel. Evening visit to Birla Temple and Chokhi Dhani ethnic village for folk dances and authentic Rajasthani Thali.',
        meals: ['Dinner'],
        hotelStay: 'Heritage Palace Jaipur',
      },
      {
        day: 2,
        title: 'Jaipur Forts & Palaces Exploration',
        description: 'Morning excursion to majestic Amber Fort with jeep safari. Photo stop at Jal Mahal. Afternoon visit to City Palace, Jantar Mantar observatory, and iconic Hawa Mahal.',
        meals: ['Breakfast', 'Dinner'],
        hotelStay: 'Heritage Palace Jaipur',
      },
      {
        day: 3,
        title: 'Jaipur to Jodhpur: The Blue City',
        description: 'Drive to Jodhpur with lunch en route. Visit the imposing Mehrangarh Fort perched 400 feet above the blue-washed old city. Walk through Jaswant Thada cenotaphs.',
        meals: ['Breakfast', 'Dinner'],
        hotelStay: 'Pal Haveli Jodhpur',
      },
      {
        day: 4,
        title: 'Jodhpur to Udaipur via Ranakpur Jain Temples',
        description: 'Scenic journey to Udaipur stopping at the world-renowned 15th-century marble temple of Ranakpur with 1,444 uniquely carved pillars. Arrive in Udaipur by sunset.',
        meals: ['Breakfast', 'Dinner'],
        hotelStay: 'Lakeside Palace Retreat Udaipur',
      },
      {
        day: 5,
        title: 'Udaipur City Palace & Lake Pichola Boat Cruise',
        description: 'Explore the grand City Palace complex, Jagdish Temple, and Saheliyon-ki-Bari royal gardens. Evening romantic boat ride on Lake Pichola past Jag Mandir Island.',
        meals: ['Breakfast', 'Dinner'],
        hotelStay: 'Lakeside Palace Retreat Udaipur',
      },
      {
        day: 6,
        title: 'Departure from Udaipur',
        description: 'Check out after breakfast and transfer to Udaipur Maharana Pratap Airport.',
        meals: ['Breakfast'],
      },
    ],
    inclusions: [
      '5 Nights in curated 4-star/5-star heritage hotels',
      'Daily breakfast and royal dinners',
      'Private air-conditioned chauffeur-driven vehicle throughout',
      'English-speaking monument guides and Lake Pichola boat cruise tickets',
      'All toll, parking, and driver allowances',
    ],
    exclusions: ['Airfare', 'Monument entry fees', 'Personal expenses'],
    departureDates: ['2026-10-20', '2026-11-10', '2026-11-25', '2026-12-15'],
    images: [
      'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1200&q=80',
    ],
    isPublished: true,
    featured: true,
  },
  {
    id: 'pkg_himachal_snow_safari',
    title: 'Himachal Snow Valley & Solang Adventure Expedition',
    slug: 'himachal-snow-valley-solang-expedition',
    destinationId: 'dest_manali',
    destinationName: 'Manali',
    agentName: 'Himalayan Highs Adventures',
    durationDays: 5,
    durationNights: 4,
    pricePerTraveller: 14999,
    originalPrice: 19999,
    maxGroupSize: 15,
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Manali & Local Acclimatization',
        description: 'Pick up from Volvo bus stand or Bhuntar Airport. Check in to pine chalet. Afternoon visit to ancient Hadimba Devi Temple, Vashisht Hot Sulphur Springs, and Mall Road shopping.',
        meals: ['Dinner'],
        hotelStay: 'Whispering Pines Manali',
      },
      {
        day: 2,
        title: 'Solang Valley Snow Activities & Atal Tunnel Ride',
        description: 'Full day adventure at Solang Valley. Enjoy snow tubing, quad biking, and cable car ropeway. Drive through the engineering wonder Atal Tunnel into Lahaul Sissu valley.',
        meals: ['Breakfast', 'Dinner'],
        hotelStay: 'Whispering Pines Manali',
      },
      {
        day: 3,
        title: 'Kasol & Manikaran Gurudwara Excursion',
        description: 'Day trip to Parvati Valley, visiting the bohemian town of Kasol, riverside cafes, and the sacred Manikaran natural hot springs and Gurudwara.',
        meals: ['Breakfast', 'Dinner'],
        hotelStay: 'Whispering Pines Manali',
      },
      {
        day: 4,
        title: 'Naggar Castle & River Rafting in Kullu',
        description: 'Visit the historic wooden Naggar Castle and Nicholas Roerich Art Gallery. Thrilling white-water river rafting in Beas River at Kullu.',
        meals: ['Breakfast', 'Dinner'],
        hotelStay: 'Whispering Pines Manali',
      },
      {
        day: 5,
        title: 'Farewell Manali & Onward Departure',
        description: 'Free morning for souvenir shopping on Mall Road. Afternoon drop to bus stand/airport.',
        meals: ['Breakfast'],
      },
    ],
    inclusions: [
      '4 Nights chalet stay with mountain views',
      'Daily breakfast and hot dinners',
      'Dedicated private vehicle for all excursions',
      'Bonfire evening with music',
      'River rafting gear and guided safety',
    ],
    exclusions: ['Snow dress rental', 'Paragliding and optional adventure fees'],
    departureDates: ['2026-10-18', '2026-10-28', '2026-11-15', '2026-12-05'],
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80',
    ],
    isPublished: true,
    featured: true,
  },
];

export const sampleServices: ServiceItem[] = [
  {
    id: 'srv_airport_cab_delhi',
    title: 'Airport Express Luxury Cab Transfer',
    category: 'cab',
    description: 'Chauffeur-driven premium sedan transfer from/to airport with 60 mins flight tracking wait time and meet & greet.',
    destinationCity: 'New Delhi',
    price: 1299,
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=800&q=80',
    duration: 'Single Trip',
    inclusions: ['Flight tracking', 'Tolls & airport parking included', 'Bottled water & luggage assistance'],
    isAvailable: true,
  },
  {
    id: 'srv_goa_scuba',
    title: 'Scuba Diving & Grand Island Watersports Combo',
    category: 'activity',
    description: 'Boat ride to Grand Island, 20 mins PADI-certified instructor dive, underwater HD video/photos, plus parasailing & jet ski.',
    destinationCity: 'Goa',
    price: 2499,
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
    duration: 'Full Day (8 Hours)',
    inclusions: ['Equipment & training', 'Underwater video & photos', 'Buffet lunch on boat', 'Hotel pickup/drop'],
    isAvailable: true,
  },
  {
    id: 'srv_jodhpur_desert_safari',
    title: 'Sunset Desert Dune Bashing & Cultural Night',
    category: 'activity',
    description: '4x4 Jeep dune bashing across the Thar sands, camel ride into the sunset, followed by Rajasthani dinner around the campfire.',
    destinationCity: 'Jaipur',
    price: 3200,
    image: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80',
    duration: 'Evening (5 Hours)',
    inclusions: ['4x4 Dune ride', 'Camel safari', 'Campfire dinner & folk performance'],
    isAvailable: true,
  },
];

export const sampleCoupons: Coupon[] = [
  {
    id: 'cp_welcome500',
    code: 'WELCOME500',
    discountType: 'flat',
    discountValue: 500,
    minBookingAmount: 2000,
    isActive: true,
    usedCount: 142,
  },
  {
    id: 'cp_travelly10',
    code: 'TRAVELLY10',
    discountType: 'percentage',
    discountValue: 10,
    minBookingAmount: 2000,
    maxDiscount: 2000,
    isActive: true,
    usedCount: 520,
  },
  {
    id: 'cp_welcome10',
    code: 'WELCOME10',
    discountType: 'percentage',
    discountValue: 10,
    minBookingAmount: 1000,
    maxDiscount: 1500,
    isActive: true,
    usedCount: 260,
  },
  {
    id: 'cp_illusion10',
    code: 'ILLUSION10',
    discountType: 'percentage',
    discountValue: 10,
    minBookingAmount: 3000,
    maxDiscount: 2000,
    isActive: true,
    usedCount: 388,
  },
  {
    id: 'cp_summer2026',
    code: 'SUMMER2026',
    discountType: 'flat',
    discountValue: 1500,
    minBookingAmount: 10000,
    isActive: true,
    usedCount: 79,
  },
  {
    id: 'cp_flat1000',
    code: 'FLAT1000',
    discountType: 'flat',
    discountValue: 1000,
    minBookingAmount: 5000,
    isActive: true,
    usedCount: 110,
  },
];

export const sampleBanners: Banner[] = [
  {
    id: 'banner_1',
    title: 'Monsoon to Winter Escapes',
    subtitle: 'Flat ₹1,500 off on holiday packages with code SUMMER2026',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80',
    link: '/packages',
    badge: 'LIMITED TIME DEAL',
    isActive: true,
    order: 1,
  },
  {
    id: 'banner_2',
    title: 'Luxury Beach Resorts in Goa',
    subtitle: 'Book 3 nights, get complimentary airport luxury transfers',
    image: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1400&q=80',
    link: '/hotels?city=Goa',
    badge: 'TOP RATED',
    isActive: true,
    order: 2,
  },
];
