import React, { useState, useMemo } from 'react';
import {
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  Check,
  CheckCircle2,
  Copy,
  Eye,
  EyeOff,
  Globe,
  Layers,
  Moon,
  Palette,
  RotateCcw,
  Save,
  Sliders,
  Sparkles,
  Sun,
  Wand2,
} from 'lucide-react';
import { useSettings } from '../../context/SettingsContext';
import { HomepageSection } from '../../types';
import {
  evaluateContrast,
  generateAccessibleDarkVariant,
} from '../../utils/contrastUtils';
import { TravelLogo } from '../../components/common/TravelLogo';

export const AdminSiteBuilder: React.FC = () => {
  const {
    branding,
    sections,
    featureFlags,
    updateBranding,
    updateSections,
    updateFeatureFlags,
  } = useSettings();

  const [activeTab, setActiveTab] = useState<'branding' | 'sections' | 'flags'>('branding');
  const [brandingForm, setBrandingForm] = useState(branding);
  const [sectionsList, setSectionsList] = useState<HomepageSection[]>(sections);
  const [flagsForm, setFlagsForm] = useState(featureFlags);
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [saving, setSaving] = useState(false);
  const [previewMode, setPreviewMode] = useState<'split' | 'light' | 'dark'>('split');

  // Sync state when context loads
  React.useEffect(() => {
    setBrandingForm(branding);
    setSectionsList(sections);
    setFlagsForm(featureFlags);
  }, [branding, sections, featureFlags]);

  // Real-time Contrast Checks
  const lightBg = '#ffffff';
  const darkBg = '#0b1120';

  const lightPrimaryContrast = useMemo(
    () => evaluateContrast(brandingForm.primaryColor || '#0b1120', lightBg),
    [brandingForm.primaryColor]
  );

  const lightAccentContrast = useMemo(
    () => evaluateContrast(brandingForm.accentColor || '#0284c7', lightBg),
    [brandingForm.accentColor]
  );

  const darkPrimary =
    brandingForm.primaryColorDark ||
    generateAccessibleDarkVariant(brandingForm.primaryColor || '#0b1120', darkBg);

  const darkAccent =
    brandingForm.accentColorDark ||
    brandingForm.accentColor ||
    '#0284c7';

  const darkPrimaryContrast = useMemo(
    () => evaluateContrast(darkPrimary, darkBg),
    [darkPrimary]
  );

  const darkAccentContrast = useMemo(
    () => evaluateContrast(darkAccent, darkBg),
    [darkAccent]
  );

  const handleAutoGenerateDark = () => {
    const autoPrimary = generateAccessibleDarkVariant(brandingForm.primaryColor, darkBg);
    const autoAccent = generateAccessibleDarkVariant(brandingForm.accentColor, darkBg);
    setBrandingForm({
      ...brandingForm,
      primaryColorDark: autoPrimary,
      accentColorDark: autoAccent,
    });
  };

  // Section Reordering
  const moveSection = (index: number, direction: 'up' | 'down') => {
    const targetIndex = direction === 'up' ? index - 1 : index + 1;
    if (targetIndex < 0 || targetIndex >= sectionsList.length) return;

    const updated = [...sectionsList];
    const temp = updated[index];
    updated[index] = updated[targetIndex];
    updated[targetIndex] = temp;

    const reordered = updated.map((sec, i) => ({ ...sec, order: i + 1 }));
    setSectionsList(reordered);
  };

  const toggleSectionEnabled = (id: string) => {
    setSectionsList((prev) =>
      prev.map((s) => (s.id === id ? { ...s, enabled: !s.enabled } : s))
    );
  };

  const handleSaveAll = async () => {
    setSaving(true);
    try {
      await updateBranding(brandingForm);
      await updateSections(sectionsList);
      await updateFeatureFlags(flagsForm);
      setSaveSuccess(true);
      setTimeout(() => setSaveSuccess(false), 2500);
    } catch {
      // Error handled
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-black text-slate-900 dark:text-white tracking-tight">
            Site Builder & Live Theme Customizer
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
            Real-time light/dark theme colors, WCAG AA contrast compliance, and homepage layout.
          </p>
        </div>

        <div className="flex items-center gap-3">
          {saveSuccess && (
            <span className="text-xs font-bold text-emerald-600 dark:text-emerald-400 flex items-center gap-1">
              <Check className="w-4 h-4" /> Changes Applied Live
            </span>
          )}
          <button
            onClick={handleSaveAll}
            disabled={saving}
            className="flex items-center gap-2 px-6 py-2.5 bg-sky-600 hover:bg-sky-500 disabled:opacity-50 text-white font-bold text-xs rounded-xl shadow-lg shadow-sky-600/20 transition cursor-pointer"
          >
            <Save className="w-4 h-4" />
            <span>{saving ? 'Publishing...' : 'Save & Publish Live'}</span>
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex items-center gap-2 border-b border-slate-200 dark:border-slate-800 pb-3">
        <button
          onClick={() => setActiveTab('branding')}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition cursor-pointer ${
            activeTab === 'branding'
              ? 'bg-sky-600 text-white shadow-sm'
              : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800'
          }`}
        >
          <Palette className="w-4 h-4" />
          <span>Branding & Light/Dark Colors</span>
        </button>

        <button
          onClick={() => setActiveTab('sections')}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition cursor-pointer ${
            activeTab === 'sections'
              ? 'bg-sky-600 text-white shadow-sm'
              : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800'
          }`}
        >
          <Layers className="w-4 h-4" />
          <span>Homepage Sections Order</span>
        </button>

        <button
          onClick={() => setActiveTab('flags')}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition cursor-pointer ${
            activeTab === 'flags'
              ? 'bg-sky-600 text-white shadow-sm'
              : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800'
          }`}
        >
          <Sliders className="w-4 h-4" />
          <span>Feature Flags</span>
        </button>
      </div>

      {/* TAB 1: BRANDING & THEME */}
      {activeTab === 'branding' && (
        <div className="space-y-8">
          {/* Form Card */}
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 sm:p-8 space-y-6">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
                  Brand Name
                </label>
                <input
                  type="text"
                  value={brandingForm.brandName}
                  onChange={(e) => setBrandingForm({ ...brandingForm, brandName: e.target.value })}
                  className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-bold text-slate-900 dark:text-white focus:outline-hidden focus:border-sky-500"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
                  Tagline
                </label>
                <input
                  type="text"
                  value={brandingForm.tagline}
                  onChange={(e) => setBrandingForm({ ...brandingForm, tagline: e.target.value })}
                  className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm text-slate-800 dark:text-slate-200 focus:outline-hidden focus:border-sky-500"
                />
              </div>

              {/* Logo Settings for Light & Dark */}
              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
                  Light Mode Logo URL (Default)
                </label>
                <input
                  type="text"
                  value={brandingForm.logoUrl}
                  onChange={(e) => setBrandingForm({ ...brandingForm, logoUrl: e.target.value })}
                  placeholder="/icon.svg or https://..."
                  className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm text-slate-800 dark:text-white focus:outline-hidden focus:border-sky-500"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
                  Dark Mode Logo URL (Optional override)
                </label>
                <input
                  type="text"
                  value={brandingForm.logoUrlDark || ''}
                  onChange={(e) =>
                    setBrandingForm({ ...brandingForm, logoUrlDark: e.target.value })
                  }
                  placeholder="Falls back to light logo if empty"
                  className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm text-slate-800 dark:text-white focus:outline-hidden focus:border-sky-500"
                />
              </div>
            </div>

            {/* Color Palette & WCAG AA Contrast Checks */}
            <div className="pt-6 border-t border-slate-100 dark:border-slate-800">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-6">
                <div>
                  <h3 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2">
                    <Palette className="w-4 h-4 text-sky-500" />
                    <span>Dynamic Palette & WCAG AA Contrast Checks</span>
                  </h3>
                  <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                    Requires 4.5:1 contrast for normal body text and 3:1 for large text / UI elements.
                  </p>
                </div>

                <button
                  type="button"
                  onClick={handleAutoGenerateDark}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-sky-50 dark:bg-sky-500/10 text-sky-600 dark:text-sky-400 border border-sky-500/20 text-xs font-bold hover:bg-sky-100 dark:hover:bg-sky-500/20 transition cursor-pointer"
                >
                  <Wand2 className="w-3.5 h-3.5" />
                  <span>Auto-Compute Dark Palette</span>
                </button>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Light Mode Colors */}
                <div className="bg-slate-50 dark:bg-slate-800/60 p-5 rounded-2xl border border-slate-200 dark:border-slate-700 space-y-4">
                  <div className="flex items-center gap-2 text-xs font-bold text-slate-900 dark:text-white pb-2 border-b border-slate-200 dark:border-slate-700">
                    <Sun className="w-4 h-4 text-amber-500" />
                    <span>Light Mode Colors (Background: #FFFFFF)</span>
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
                      Primary Color
                    </label>
                    <div className="flex items-center gap-2">
                      <input
                        type="color"
                        value={brandingForm.primaryColor}
                        onChange={(e) =>
                          setBrandingForm({ ...brandingForm, primaryColor: e.target.value })
                        }
                        className="w-9 h-9 rounded-lg border-none cursor-pointer"
                      />
                      <input
                        type="text"
                        value={brandingForm.primaryColor}
                        onChange={(e) =>
                          setBrandingForm({ ...brandingForm, primaryColor: e.target.value })
                        }
                        className="flex-1 p-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-mono text-slate-900 dark:text-white"
                      />
                    </div>
                    <div className="mt-1 flex items-center justify-between text-[11px]">
                      <span className="text-slate-500">Contrast vs #FFF:</span>
                      <span
                        className={`font-bold flex items-center gap-1 ${
                          lightPrimaryContrast.passAA ? 'text-emerald-600' : 'text-amber-500'
                        }`}
                      >
                        {lightPrimaryContrast.passAA ? (
                          <CheckCircle2 className="w-3 h-3" />
                        ) : (
                          <AlertTriangle className="w-3 h-3" />
                        )}
                        {lightPrimaryContrast.ratio}:1 ({lightPrimaryContrast.score})
                      </span>
                    </div>
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
                      Accent Action Color
                    </label>
                    <div className="flex items-center gap-2">
                      <input
                        type="color"
                        value={brandingForm.accentColor}
                        onChange={(e) =>
                          setBrandingForm({ ...brandingForm, accentColor: e.target.value })
                        }
                        className="w-9 h-9 rounded-lg border-none cursor-pointer"
                      />
                      <input
                        type="text"
                        value={brandingForm.accentColor}
                        onChange={(e) =>
                          setBrandingForm({ ...brandingForm, accentColor: e.target.value })
                        }
                        className="flex-1 p-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-mono text-slate-900 dark:text-white"
                      />
                    </div>
                    <div className="mt-1 flex items-center justify-between text-[11px]">
                      <span className="text-slate-500">Contrast vs #FFF:</span>
                      <span
                        className={`font-bold flex items-center gap-1 ${
                          lightAccentContrast.passAALarge ? 'text-emerald-600' : 'text-amber-500'
                        }`}
                      >
                        {lightAccentContrast.passAALarge ? (
                          <CheckCircle2 className="w-3 h-3" />
                        ) : (
                          <AlertTriangle className="w-3 h-3" />
                        )}
                        {lightAccentContrast.ratio}:1 ({lightAccentContrast.score})
                      </span>
                    </div>
                  </div>
                </div>

                {/* Dark Mode Colors */}
                <div className="bg-slate-50 dark:bg-slate-800/60 p-5 rounded-2xl border border-slate-200 dark:border-slate-700 space-y-4">
                  <div className="flex items-center gap-2 text-xs font-bold text-slate-900 dark:text-white pb-2 border-b border-slate-200 dark:border-slate-700">
                    <Moon className="w-4 h-4 text-sky-400" />
                    <span>Dark Mode Overrides (Background: #0B1120)</span>
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
                      Dark Primary Variant
                    </label>
                    <div className="flex items-center gap-2">
                      <input
                        type="color"
                        value={darkPrimary}
                        onChange={(e) =>
                          setBrandingForm({ ...brandingForm, primaryColorDark: e.target.value })
                        }
                        className="w-9 h-9 rounded-lg border-none cursor-pointer"
                      />
                      <input
                        type="text"
                        value={darkPrimary}
                        onChange={(e) =>
                          setBrandingForm({ ...brandingForm, primaryColorDark: e.target.value })
                        }
                        className="flex-1 p-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-mono text-slate-900 dark:text-white"
                      />
                    </div>
                    <div className="mt-1 flex items-center justify-between text-[11px]">
                      <span className="text-slate-500">Contrast vs #0B1120:</span>
                      <span
                        className={`font-bold flex items-center gap-1 ${
                          darkPrimaryContrast.passAA ? 'text-emerald-500' : 'text-amber-500'
                        }`}
                      >
                        {darkPrimaryContrast.passAA ? (
                          <CheckCircle2 className="w-3 h-3" />
                        ) : (
                          <AlertTriangle className="w-3 h-3" />
                        )}
                        {darkPrimaryContrast.ratio}:1 ({darkPrimaryContrast.score})
                      </span>
                    </div>
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
                      Dark Accent Action Color
                    </label>
                    <div className="flex items-center gap-2">
                      <input
                        type="color"
                        value={darkAccent}
                        onChange={(e) =>
                          setBrandingForm({ ...brandingForm, accentColorDark: e.target.value })
                        }
                        className="w-9 h-9 rounded-lg border-none cursor-pointer"
                      />
                      <input
                        type="text"
                        value={darkAccent}
                        onChange={(e) =>
                          setBrandingForm({ ...brandingForm, accentColorDark: e.target.value })
                        }
                        className="flex-1 p-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-mono text-slate-900 dark:text-white"
                      />
                    </div>
                    <div className="mt-1 flex items-center justify-between text-[11px]">
                      <span className="text-slate-500">Contrast vs #0B1120:</span>
                      <span
                        className={`font-bold flex items-center gap-1 ${
                          darkAccentContrast.passAALarge ? 'text-emerald-500' : 'text-amber-500'
                        }`}
                      >
                        {darkAccentContrast.passAALarge ? (
                          <CheckCircle2 className="w-3 h-3" />
                        ) : (
                          <AlertTriangle className="w-3 h-3" />
                        )}
                        {darkAccentContrast.ratio}:1 ({darkAccentContrast.score})
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Live Side-by-Side Dual Theme Preview */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-sm font-bold text-slate-900 dark:text-white">
                  Live Dual-Theme Synchronous Preview
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Inspect buttons, tags, typography, and card surface elevation across both themes.
                </p>
              </div>

              {/* Preview mode segmented switch */}
              <div className="flex items-center p-1 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs">
                <button
                  type="button"
                  onClick={() => setPreviewMode('split')}
                  className={`px-3 py-1 rounded-lg font-bold transition ${
                    previewMode === 'split'
                      ? 'bg-white dark:bg-slate-700 text-sky-600 dark:text-white shadow-xs'
                      : 'text-slate-500'
                  }`}
                >
                  Side by Side
                </button>
                <button
                  type="button"
                  onClick={() => setPreviewMode('light')}
                  className={`px-3 py-1 rounded-lg font-bold transition ${
                    previewMode === 'light'
                      ? 'bg-white dark:bg-slate-700 text-sky-600 dark:text-white shadow-xs'
                      : 'text-slate-500'
                  }`}
                >
                  Light Only
                </button>
                <button
                  type="button"
                  onClick={() => setPreviewMode('dark')}
                  className={`px-3 py-1 rounded-lg font-bold transition ${
                    previewMode === 'dark'
                      ? 'bg-white dark:bg-slate-700 text-sky-600 dark:text-white shadow-xs'
                      : 'text-slate-500'
                  }`}
                >
                  Dark Only
                </button>
              </div>
            </div>

            <div
              className={`grid gap-6 ${
                previewMode === 'split'
                  ? 'grid-cols-1 md:grid-cols-2'
                  : 'grid-cols-1'
              }`}
            >
              {/* Light Mode Live Mockup */}
              {(previewMode === 'split' || previewMode === 'light') && (
                <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-md space-y-5 text-slate-900">
                  <div className="flex items-center justify-between pb-3 border-b border-slate-100">
                    <TravelLogo isDark={false} />
                    <span className="text-[10px] font-black uppercase tracking-wider px-2 py-0.5 rounded-md bg-slate-100 text-slate-700">
                      Light Mockup
                    </span>
                  </div>

                  <div className="space-y-2">
                    <span className="text-xs font-bold uppercase tracking-wider text-sky-600">
                      Curated Getaways
                    </span>
                    <h4 className="text-lg font-black text-slate-900">
                      The Grand Heritage Palace Resort
                    </h4>
                    <p className="text-xs text-slate-500 leading-relaxed">
                      Experience private infinity pools, rooftop dining, and 24/7 butler service.
                    </p>
                  </div>

                  <div className="flex items-center justify-between pt-3 border-t border-slate-100">
                    <div>
                      <span className="text-[10px] text-slate-400 block font-medium">Per night</span>
                      <span className="text-lg font-black text-slate-900">₹14,500</span>
                    </div>

                    <button
                      type="button"
                      style={{ backgroundColor: brandingForm.accentColor || '#0284c7' }}
                      className="px-4 py-2 text-white font-bold text-xs rounded-xl shadow-xs"
                    >
                      Book Suite
                    </button>
                  </div>
                </div>
              )}

              {/* Dark Mode Live Mockup */}
              {(previewMode === 'split' || previewMode === 'dark') && (
                <div className="bg-slate-950 p-6 rounded-3xl border border-slate-800 shadow-md space-y-5 text-white">
                  <div className="flex items-center justify-between pb-3 border-b border-slate-800">
                    <TravelLogo isDark={true} />
                    <span className="text-[10px] font-black uppercase tracking-wider px-2 py-0.5 rounded-md bg-slate-800 text-sky-400">
                      Dark Mockup
                    </span>
                  </div>

                  <div className="space-y-2">
                    <span
                      style={{ color: darkPrimary }}
                      className="text-xs font-bold uppercase tracking-wider"
                    >
                      Curated Getaways
                    </span>
                    <h4 className="text-lg font-black text-white">
                      The Grand Heritage Palace Resort
                    </h4>
                    <p className="text-xs text-slate-400 leading-relaxed">
                      Experience private infinity pools, rooftop dining, and 24/7 butler service.
                    </p>
                  </div>

                  <div className="flex items-center justify-between pt-3 border-t border-slate-800">
                    <div>
                      <span className="text-[10px] text-slate-400 block font-medium">Per night</span>
                      <span className="text-lg font-black text-white">₹14,500</span>
                    </div>

                    <button
                      type="button"
                      style={{ backgroundColor: darkAccent }}
                      className="px-4 py-2 text-white font-bold text-xs rounded-xl shadow-xs"
                    >
                      Book Suite
                    </button>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: HOMEPAGE SECTIONS ORDER & VISIBILITY */}
      {activeTab === 'sections' && (
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 sm:p-8 space-y-4">
          <p className="text-xs text-slate-500 dark:text-slate-400 mb-4">
            Reorder sections using the arrows. Toggle the eye button to show or hide a section from the live homepage.
          </p>

          <div className="space-y-2">
            {sectionsList.map((sec, idx) => (
              <div
                key={sec.id}
                className="flex items-center justify-between p-4 bg-slate-50 dark:bg-slate-800/80 rounded-2xl border border-slate-200 dark:border-slate-700/80"
              >
                <div className="flex items-center gap-3">
                  <span className="w-6 text-center text-xs font-mono font-bold text-slate-400">
                    #{sec.order}
                  </span>
                  <div>
                    <p className="text-sm font-bold text-slate-900 dark:text-white capitalize">
                      {sec.type.replace('_', ' ')}
                    </p>
                    <p className="text-xs text-slate-500 dark:text-slate-400 truncate max-w-xs">{sec.title}</p>
                  </div>
                </div>

                <div className="flex items-center gap-1.5">
                  <button
                    type="button"
                    disabled={idx === 0}
                    onClick={() => moveSection(idx, 'up')}
                    className="p-1.5 rounded-lg text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-20 cursor-pointer"
                  >
                    <ArrowUp className="w-4 h-4" />
                  </button>
                  <button
                    type="button"
                    disabled={idx === sectionsList.length - 1}
                    onClick={() => moveSection(idx, 'down')}
                    className="p-1.5 rounded-lg text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-20 cursor-pointer"
                  >
                    <ArrowDown className="w-4 h-4" />
                  </button>
                  <button
                    type="button"
                    onClick={() => toggleSectionEnabled(sec.id)}
                    className={`p-1.5 rounded-lg transition cursor-pointer ${
                      sec.enabled
                        ? 'text-emerald-600 dark:text-emerald-400 hover:bg-emerald-50 dark:hover:bg-emerald-500/10'
                        : 'text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700'
                    }`}
                  >
                    {sec.enabled ? <Eye className="w-4 h-4" /> : <EyeOff className="w-4 h-4" />}
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* TAB 3: FEATURE FLAGS */}
      {activeTab === 'flags' && (
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 sm:p-8 space-y-6">
          <div className="space-y-4">
            <label className="flex items-center justify-between p-4 bg-slate-50 dark:bg-slate-800/80 rounded-2xl border border-slate-200 dark:border-slate-700 cursor-pointer">
              <div>
                <p className="text-sm font-bold text-slate-900 dark:text-white">Enable Online Gateway Payment</p>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Allow customers to pay via card or UPI in addition to pay upon arrival.
                </p>
              </div>
              <input
                type="checkbox"
                checked={flagsForm.enableOnlinePayment}
                onChange={(e) => setFlagsForm({ ...flagsForm, enableOnlinePayment: e.target.checked })}
                className="w-5 h-5 accent-sky-600 rounded-md cursor-pointer"
              />
            </label>

            <label className="flex items-center justify-between p-4 bg-slate-50 dark:bg-slate-800/80 rounded-2xl border border-slate-200 dark:border-slate-700 cursor-pointer">
              <div>
                <p className="text-sm font-bold text-slate-900 dark:text-white">Enable Tour Agent Applications</p>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Allow external certified travel agencies to list curated tours.
                </p>
              </div>
              <input
                type="checkbox"
                checked={flagsForm.enableAgents}
                onChange={(e) => setFlagsForm({ ...flagsForm, enableAgents: e.target.checked })}
                className="w-5 h-5 accent-sky-600 rounded-md cursor-pointer"
              />
            </label>

            <label className="flex items-center justify-between p-4 bg-slate-50 dark:bg-slate-800/80 rounded-2xl border border-slate-200 dark:border-slate-700 cursor-pointer">
              <div>
                <p className="text-sm font-bold text-slate-900 dark:text-white">Emergency Maintenance Mode</p>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Puts an announcement banner at top while preserving all database safeguards.
                </p>
              </div>
              <input
                type="checkbox"
                checked={flagsForm.maintenanceMode}
                onChange={(e) => setFlagsForm({ ...flagsForm, maintenanceMode: e.target.checked })}
                className="w-5 h-5 accent-amber-600 rounded-md cursor-pointer"
              />
            </label>
          </div>
        </div>
      )}
    </div>
  );
};
